name: DL Automation Trigger

on:
  repository_dispatch:
    types: [dl_ticket_created]

jobs:
  run-dl-automation:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PowerShell Core
        uses: actions/setup-powershell@v4

      - name: Run DL automation script
        shell: pwsh
        env:
          AZURE_CERT_BASE64: ${{ secrets.AZURE_CERT_BASE64 }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
          APP_ID: ${{ secrets.APP_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          ORGANIZATION: ${{ secrets.ORGANIZATION }}
        run: |
          $dgName = "${{ github.event.client_payload.DistributionGroupName }}"
          $owners  = "${{ github.event.client_payload.NewOwner_EmailAddress }}"
          ./scripts/handle-dl-ticket.ps1 `
            -DistributionGroupName $dgName `
            -NewOwner_EmailAddress $owners
