name: DL Automation Trigger

on:
  repository_dispatch:
    types: [dl_ticket_created]

jobs:
  run-dl-automation:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Install and Import ExchangeOnlineManagement Module
      - name: Install ExchangeOnlineManagement module
        shell: pwsh
        run: |
          Write-Host "📦 Installing ExchangeOnlineManagement module..."
          Install-Module -Name ExchangeOnlineManagement -Force -AllowClobber -Scope CurrentUser
          Import-Module ExchangeOnlineManagement
          Write-Host "✅ ExchangeOnlineManagement module installed and imported."

      # ✅ Run DL automation PowerShell script
      - name: Run DL automation script
        shell: pwsh
        env:
          CERT_BASE64: ${{ secrets.CERT_BASE64 }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
          APP_ID: ${{ secrets.APP_ID }}
          CERT_THUMBPRINT: ${{ secrets.CERT_THUMBPRINT }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          ORGANIZATION: ${{ secrets.ORGANIZATION }}
        run: |
