name: Exchange Online - App Cert Connection

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  connect-exchange:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PowerShell (preinstalled on windows-latest)
        uses: actions/setup-powershell@v2

      - name: Run Exchange connection script
        shell: pwsh
        env:
          APP_ID: ${{ secrets.APP_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CERT_THUMBPRINT: ${{ secrets.CERT_THUMBPRINT }}
          CERT_BASE64: ${{ secrets.CERT_BASE64 }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        run: |
          # Optional: show PowerShell version
          pwsh -NoLogo -Command '$PSVersionTable.PSVersion'

          # Run the script with the secrets passed as arguments
          pwsh ./exchange-connect.ps1 `
            -AppId $env:APP_ID `
            -TenantId $env:TENANT_ID `
            -Thumbprint $env:CERT_THUMBPRINT `
            -CertBase64 $env:CERT_BASE64 `
            -CertPassword $env:CERT_PASSWORD
