name: Exchange Online - App Cert Connection

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  connect-exchange:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Show PowerShell version (correct syntax)
      - name: Show PowerShell version
        run: pwsh -NoLogo -Command "$PSVersionTable.PSVersion"

      # ✅ (Optional) Install ExchangeOnlineManagement module
      - name: Install Exchange Online PowerShell module
        run: pwsh -Command "Install-Module ExchangeOnlineManagement -Force -AllowClobber -Scope CurrentUser"

      # ✅ Run your PowerShell script with certificate details
      - name: Run Exchange connection script
        shell: pwsh
        env:
          APP_ID: ${{ secrets.APP_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CERT_THUMBPRINT: ${{ secrets.CERT_THUMBPRINT }}
          CERT_BASE64: ${{ secrets.CERT_BASE64 }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        run: |
          pwsh ./exchange-connect.ps1 `
            -AppId $env:APP_ID `
            -TenantId $env:TENANT_ID `
            -Thumbprint $env:CERT_THUMBPRINT `
            -CertBase64 $env:CERT_BASE64 `
            -CertPassword $env:CERT_PASSWORD
